spring.application.name=atlantis-fest
spring.datasource.url=jdbc:mariadb://localhost:3306/${APP_DB_NAME:atlantis_db}
spring.datasource.username=${APP_DB_USER:miwi}
spring.datasource.password=${APP_DB_PASS:miwiUser}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# db JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.config.import=optional:file:.env,optional:file:.env.properties
#Upload cfg
file.upload-dir=uploads/
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1
