spring.application.name=atlantis-fest
spring.datasource.url=jdbc:mariadb://localhost:3306/${APP_DB_NAME}?createDatabaseIfNotExist=true
spring.datasource.username=${APP_DB_USER}
spring.datasource.password=${APP_DB_PASS}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# db JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

spring.config.import=optional:file:.env.properties